### ISSUE TITLE
feat: add support for multi-column characters

### ISSUE THREAD

**Issue by ickc** [basverweij/markdown-it-gridtables#18]
Reporting from a downstream package, copied below from <https://marketplace.visualstudio.com/items?itemName=ickc.vscode-markdown-it-pandoc&ssr=false#review-details>:

> when use Chinese character in grid table, rendering in vscode build-in preview is wrong when grid border '|' is aligned.

```markdown
+--------------+-------+
|000Fruits00000|0Price0|
+==============+=======+
|0香蕉水果价格0|01.3400|
+--------------+-------+
|0Oranges000000|0$2.100|
+--------------+-------+
```

Thanks.

**Comment by basverweij** [comment]
Hi @ickc! The `markdown-it-gridtables` plugin only looks at the _number_ of characters in any cell - for each line this must be equal to the number of characters in the _first_ line of the table to allow the plugin to transform it into an HTML table.

In the example that you provided, the first line of the table has 14 characters in the first column, and the second column has 7 characters.

This means that the first cell of the second row (containing the Chinese characters) must also contain 14 characters, but in your example it only has 8. Adding an additional 6 characters fixes this:

```markdown
+--------------+-------+
|000Fruits00000|0Price0|
+==============+=======+
|0香蕉水果价格0111111|01.3400|
+--------------+-------+
|0Oranges000000|0$2.100|
+--------------+-------+
```

Which is rendered as:

![image](https://user-images.githubusercontent.com/9398734/158057754-4866dafe-3391-4fc6-8281-ab8847cc9684.png)

**Comment by ickc** [comment]
But I think CJK characters are often treated at 2 character wide. This is how pandoc counts for example. And for Chinese input, we call Chinese character and other English-like character with Chinese character width 全形 and ASCII characters and the like as 半形. Literally it means full width and half width, another angle to see how Chinese character is double of ASCII character width.

(I agree it is complicated but I didn’t make those rules. I don’t even know how other Unicode width should be treated if there are other exceptions.)

**Comment by basverweij** [comment]
@ickc Alright- I'll have a go at it and see whether I can account for characters that have a double width!

I'm going to use this package to provide the necessary information: https://www.npmjs.com/package/wcwidth

**Comment by basverweij** [comment]
@ickc [v0.4.0](https://github.com/basverweij/markdown-it-gridtables/releases/tag/v0.4.0) should now properly support multi-column characters!

![image](https://user-images.githubusercontent.com/9398734/160236780-741b87d7-a863-455c-9baa-3e15cb095ed9.png)
